namespace XtremeIdiots.Portal.Web.Services;

/// <summary>
/// Result of validating an external HMAC-signed token from the forum
/// </summary>
public record ExternalTokenResult(bool IsValid, string? ForumMemberId, string? Error);

/// <summary>
/// Validates HMAC-signed tokens generated by the forum to authenticate external widget requests
/// </summary>
public interface IExternalTokenService
{
    /// <summary>
    /// Validates an HMAC-SHA256 signed token containing a forum member ID and timestamp
    /// </summary>
    /// <param name="token">Base64-encoded token in format {forumMemberId}:{timestampUnix}:{hmac}</param>
    /// <returns>Validation result with the forum member ID if valid</returns>
    ExternalTokenResult ValidateToken(string token);
}
